skip-check:
  - CKV_AWS_18  # AWS Access logging not enabled on S3 buckets - need this to test the option to not enable logging
  - 806079905565028352_AWS_1661102300011 # AWS Access logging not enabled on S3 buckets
