default_language_version:
  node: system

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        args:
          - --unsafe # needed for parsing CFN
      - id: end-of-file-fixer
      - id: file-contents-sorter
        args: [--unique]
        files: |
          (?x)^(
            \.dockerignore|
            \.gitignore
          )$
      - id: pretty-format-json
        args: [--autofix, --indent, '4']
        files: |
          (?x)^(
            \.gitlab/.*\.json|
            \.vscode/.*\.json
          )$
      - id: pretty-format-json
        args: [--autofix, --indent, '2']
        files: |
          (?x)^(
            (.*)?(cdk|tsconfig|tslint).json
          )$
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/ITProKyle/pre-commit-hook-yamlfmt
    rev: v0.2.1
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --offset, '2', --sequence, '4']
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-tables
          - mdformat-toc
        exclude: |
          (?x)^(
            \.gitlab/merge_request_templates/.*\.md
          )$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
