repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
        exclude: |
          (?x)^(
            integration/.*|
            cfngin/templates/.*|
            .*/site-packages/.*|
            .*/venv/.*
          )$
      - id: check-merge-conflict
        exclude: |
          (?x)^(
            integration/.*|
            cfngin/templates/.*|
            .*/site-packages/.*|
            .*/venv/.*
          )$
      - id: check-yaml
        args:
          - --unsafe  # needed for parsing CFN
        exclude: |
          (?x)^(
            integration/.*|
            cfngin/templates/.*|
            .*/site-packages/.*|
            .*/venv/.*
          )$
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            integration/.*|
            cfngin/templates/.*|
            .*/site-packages/.*|
            .*/venv/.*
          )$
      - id: file-contents-sorter
        args: [--unique]
        files: |
          (?x)^(
            \.dockerignore|
            \.gitignore
          )$
        exclude: |
          (?x)^(
            integration/.*|
            cfngin/templates/.*|
            .*/site-packages/.*|
            .*/venv/.*
          )$
      - id: pretty-format-json
        args: [--autofix, --indent, '4']
        files: |
          (?x)^(
            \.vscode/.*\.json|
            test/fixtures/.*\.json
          )$
        exclude: |
          (?x)^(
            integration/.*|
            cfngin/templates/.*|
            .*/site-packages/.*|
            .*/venv/.*
          )$
      - id: trailing-whitespace
        exclude: |
          (?x)^(
            integration/.*|
            cfngin/templates/.*|
            .*/site-packages/.*|
            .*/venv/.*
          )$
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: |
          (?x)^(
            integration/.*|
            cfngin/templates/.*|
            .*/site-packages/.*|
            .*/venv/.*
          )$
  - repo: https://github.com/psf/black
    rev: 24.4.0
    hooks:
      - id: black
        exclude: |
          (?x)^(
            integration/.*|
            cfngin/templates/.*|
            .*/site-packages/.*|
            .*/venv/.*
          )$
  - repo: https://github.com/PyCQA/flake8.git
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=120, --ignore=E501]
        exclude: |
          (?x)^(
            integration/.*|
            cfngin/templates/.*|
            .*/site-packages/.*|
            .*/venv/.*
          )$
  - repo: https://github.com/ITProKyle/pre-commit-hook-yamlfmt
    rev: v0.2.1
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --offset, '2', --sequence, '4']
        exclude: stacker.yaml
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        exclude: |
          (?x)^(
            \.gitlab/merge_request_templates/default\.md|
            CHANGELOG\.md
          )$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: [--disable, MD013]
        exclude: |
          (?x)^(
            CHANGELOG\.md|
            integration/.*|
            cfngin/templates/.*|
            .*/site-packages/.*|
            .*/venv/.*
          )$
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.2
    hooks:
      - id: poetry-check
        exclude: |
          (?x)^(
            integration/.*|
            cfngin/templates/.*|
            .*/site-packages/.*|
            .*/venv/.*
          )$
