AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Commodity Bags CloudWatch Alarm Lambda

Parameters:
  pDepartment:
    Type: String
    AllowedPattern: '[a-z][a-z0-9-]*'
    ConstraintDescription: Must start with a letter and be all lowercase
    Description: The department Name for the Account (crew, opssuite, dotcom, etc.)

  pNamespace:
    Type: String
    AllowedPattern: '[a-z][a-z0-9-]*'
    ConstraintDescription: Must start with a letter and be all lowercase
    Description: The Namespace or Platform Instance

  pDashApplication:
    Type: String
    Description: DASH Application

  pDashAssignmentGroup:
    Type: String
    Description: DASH Assignment Group

  pIamRole:
    Type: String
    Description: Commodity Project wide IAM role

  pEnableDashNotif:
    Type: String
    Description: Enables / Disables Dash notifications

  pEnableEmailNotif:
    Type: String
    Description: Enables / Disables Email notifications

  pDatalakeNamespace:
    Type: String
    AllowedPattern: '[a-z][a-z0-9-]*'
    ConstraintDescription: Must start with a letter and be all lowercase
    Description: The Namespace or Platform Instance for the datalake

  pGlueRejectsBucketPrefix:
    Type: String
    Description: The bucket name that is used for storing rejects found during execution of glue jobs

  pGlueRejectsBucketSuffix:
    Type: String
    Description: The generic name that is appended to the end of the s3 bucket for storing rejects

  pGlueRejectsKeyPrefix:
    Type: String
    Description: The s3 prefix that is used for the reject data created by glue jobs

  pCodeUriBucket:
    Type: String
    Description: S3 Bucket where code resides

  pCodeUriKey:
    Type: String
    Description: Path within S3 bucket where code resides

Resources:
  rCmdtyBagsDashAlerts:
    Type: AWS::Serverless::Function
    Properties:
      Handler: sns_alerts.lambda_handler
      CodeUri:
        Bucket: !Ref pCodeUriBucket
        Key: !Ref pCodeUriKey
      Runtime: python3.9
      FunctionName: !Sub "${pDepartment}-${pNamespace}-cmdty-bags-sns-alerts"
      Role: !Sub "${pIamRole}"
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${pDepartment}-${pNamespace}-cmdty-Bags-sns-alerts-notify"
          DASH_SNS_TOPIC_ARN: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:cw_medium_alarm_sns_to_dash"
          DASH_APPLICATION: !Sub "${pDashApplication}"
          DASH_ASSIGNMENT_GROUP: !Sub "${pDashAssignmentGroup}"
          ENABLE_DASH_NOTIFICATIONS: !Sub "${pEnableDashNotif}"
          ENABLE_EMAIL_NOTIFICATIONS: !Sub "${pEnableEmailNotif}"
          DATALAKE_NAMESPACE: !Sub "${pDatalakeNamespace}"
          REJECTS_BUCKET: !Sub "${pGlueRejectsBucketPrefix}-${pGlueRejectsBucketSuffix}"
          REJECTS_PREFIX: !Sub "${pGlueRejectsKeyPrefix}"
      Timeout: 300

Outputs:
  oCmdtyBagsDashAlerts:
    Description: Lambda to monitor glue jobs, state machine, dead letter queues, etc...
    Value: !Ref 'rCmdtyBagsDashAlerts'

  oCmdtyBagsDashAlertsARN:
    Description: ARN of Lambda to monitor glue jobs, state machine, dead letter queues, etc...
    Value: !GetAtt 'rCmdtyBagsDashAlerts.Arn'
